#
# Build CI file
# Change the variables in this section to match your project
#

name: Platform Monitor - CI Build
env:
  PROJECT_NAME: PlatformMonitor
  CONFIGURATION: Release

defaults:
  run:
    working-directory: ./PlatformMonitor

#
# Everything below this is template code
#

on:
  push:
    branches-ignore: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    uses: DarkFactorAS/Infrastructure/.github/workflows/infrastructure-server-ci.yml@v1.1
    with:
      project_path: "./PlatformMonitor"
      project_name: "PlatformMonitor"
    secrets: inherit