#
# Build Deploy file for Docker container
# Change the variables in this section to match your project
#

name: Platform Monitor - Deploy

defaults:
  run:
    working-directory: ./PlatformMonitor
    
#
# Everything below this is template code
#

on:
  release:
    types: [published]

  pull_request:
    types: [closed]
    branches: ["master"]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  staging:
    if: github.event.pull_request.merged == true || github.event.inputs.environment == 'staging' || github.event.inputs.environment == 'production'
    name: Deploy to Staging
    uses: ./.github/workflows/platform_server_step.yml
    with:
      environment: staging
      source_folder: PlatformMonitor
      docker_file: ./PlatformMonitor/Dockerfile_GitHubActions
    secrets: inherit

  production:
    if: github.event.pull_request.merged == true || github.event.inputs.environment == 'production' || github.event_name == 'release'
    name: Deploy to Production
    uses: ./.github/workflows/platform_server_step.yml
    with:
      environment: production
      source_folder: PlatformMonitor
      docker_file: ./PlatformMonitor/Dockerfile_GitHubActions
    secrets: inherit
    needs: staging
